name: Check demo
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "demo/**"
      - ".github/workflows/check_demo.yml"
  push:
    paths:
      - "demo/**"
      - ".github/workflows/check_demo.yml"
defaults:
  run:
    working-directory: ./demo

jobs:
  check:
    name: lint and check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - uses: actions/cache@v3
        id: cache-deps
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-modules-${{ hashFiles('**/yarn.lock') }}
      
      - uses: borales/actions-yarn@v4
        with:
          cmd: install

      - uses: borales/actions-yarn@v4
        with:
          cmd: check
      
      - uses: borales/actions-yarn@v4
        with:
          cmd: tsc

      - uses: borales/actions-yarn@v4
        with:
          cmd: build
