name: Check demo
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "demo/**"
      - ./.github/workflows/check_demo.yml
  push:
    paths:
      - "demo/**"
      - ./.github/workflows/check_demo.yml
defaults:
  run:
    working-directory: ./demo
jobs:
  check:
    name: lint and check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-modules-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
      - run: npm run lint && npm run check
      - run: npm run build
