name: Publish
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"
jobs:
  publish:
    name: test on Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version:
          - 18
          - 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - uses: actions/cache@v3
        id: cache-deps
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-modules-${{ hashFiles('**/yarn.lock') }}
      
      - uses: borales/actions-yarn@v4
        with:
          cmd: install

      - uses: borales/actions-yarn@v4
        with:
          cmd: lint

      - uses: borales/actions-yarn@v4
        with:
          cmd: check
      
      - uses: borales/actions-yarn@v4
        with:
          cmd: tsc

      - uses: borales/actions-yarn@v4
        with:
          cmd: build

      - uses: borales/actions-yarn@v4
        with:
          cmd: test

      - uses: heinrichreimer/github-changelog-generator-action@v2.3
        if: matrix.node-version == 12
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: JS-DevTools/npm-publish@v1
        if: matrix.node-version == 12
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') && matrix.node-version == 12
        with:
          generate_release_notes: true
